=== AloyseSECK/portfolio_django/portfolio/templates/structure.dtd
<!ELEMENT cv (informations_personnelles, experience_professionnelle, formation, competences, interets)>
<!ELEMENT informations_personnelles (nom, prenom, date_de_naissance, adresse, contact)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT prenom (#PCDATA)>
<!ELEMENT date_de_naissance (#PCDATA)>
<!ELEMENT adresse (rue, ville, code_postal, pays)>
<!ELEMENT rue (#PCDATA)>
<!ELEMENT ville (#PCDATA)>
<!ELEMENT code_postal (#PCDATA)>
<!ELEMENT pays (#PCDATA)>
<!ELEMENT contact (telephone, email)>
<!ELEMENT telephone (#PCDATA)>
<!ELEMENT email (#PCDATA)>

<!ELEMENT experience_professionnelle (emploi+)>
<!ELEMENT emploi (titre, entreprise, ville, pays, date_debut, date_fin, description)>
<!ELEMENT titre (#PCDATA)>
<!ELEMENT entreprise (#PCDATA)>
<!ELEMENT date_debut (#PCDATA)>
<!ELEMENT date_fin (#PCDATA)>
<!ELEMENT description (#PCDATA)>

<!ELEMENT formation (diplome+)>
<!ELEMENT diplome (niveau, specialite, institution, ville, pays, date_obtention)>
<!ELEMENT niveau (#PCDATA)>
<!ELEMENT specialite (#PCDATA)>
<!ELEMENT institution (#PCDATA)>
<!ELEMENT date_obtention (#PCDATA)>

<!ELEMENT competences (technique, linguistique)>
<!ELEMENT technique (competence+)>
<!ELEMENT competence (#PCDATA)>

<!ELEMENT linguistique (langue,niveau)+>
<!ELEMENT langue (#PCDATA)>
<!ELEMENT interets (interet+)>
<!ELEMENT interet (#PCDATA)>

=== AloyseSECK/portfolio_django/portfolio/templates/cv.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="{% static 'portfolio/xslt/cv_style.xslt' %}"?>
<!DOCTYPE cv SYSTEM "structure.dtd">
<cv>
  <informations_personnelles>
    <nom>SECK</nom>
    <prenom>Aloyse</prenom>
    <date_de_naissance>12/11/2000</date_de_naissance>
    <adresse>
      <rue>123 rue de la République</rue>
      <ville>Paris</ville>
      <code_postal>75001</code_postal>
      <pays>France</pays>
    </adresse>
    <contact>
      <telephone>0601410798</telephone>
      <email>aloyse.seck@edu.univ-paris13.fr</email>
    </contact>
  </informations_personnelles>
  <experience_professionnelle>
    <emploi>
      <titre>Ingénieur logiciel</titre>
      <entreprise>TechnoWeb</entreprise>
      <ville>Paris</ville>
      <pays>France</pays>
      <date_debut>01/01/2015</date_debut>
      <date_fin>31/12/2019</date_fin>
      <description>Développement et maintenance de solutions logicielles.</description>
    </emploi>
    <emploi>
      <titre>Développeur web</titre>
      <entreprise>WebSolutions</entreprise>
      <ville>Lyon</ville>
      <pays>France</pays>
      <date_debut>01/02/2013</date_debut>
      <date_fin>31/12/2014</date_fin>
      <description>Conception et réalisation de sites web.</description>
    </emploi>
  </experience_professionnelle>
  <formation>
    <diplome>
      <niveau>Master</niveau>
      <specialite>Informatique</specialite>
      <institution>Université de Technologie</institution>
      <ville>Paris</ville>
      <pays>France</pays>
      <date_obtention>2012</date_obtention>
    </diplome>
  </formation>
  <competences>
    <technique>
      <competence>Java</competence>
      <competence>Python</competence>
      <competence>HTML/CSS</competence>
      <competence>JavaScript</competence>
    </technique>
    <linguistique>
      <langue>Français</langue>
      <niveau>C2</niveau>
      <langue>Anglais</langue>
      <niveau>B2</niveau>
    </linguistique>
  </competences>
  <interets>
    <interet>Programmation</interet>
    <interet>Basketball</interet>
    <interet>Voyage</interet>
  </interets>
</cv>
