=== AloyseSECK/portfolio_django/portfolio/templates/structure_cv.dtd
<!ELEMENT resume (personalInfo, objective, projects, education, languages, skills, attributes, interests, links)>
<!ELEMENT personalInfo (name, title, contact, availability)>
<!ELEMENT contact (phone, email, location)>
<!ELEMENT objective (#PCDATA | duration)*>
<!ELEMENT projects (project+)>
<!ELEMENT project (title, institution, date?, description, tools)>
<!ELEMENT education (degree+)>
<!ELEMENT degree (title, institution, date)>
<!ELEMENT languages (language+)>
<!ELEMENT language (name, level)>
<!ELEMENT skills (category+)>
<!ELEMENT category (skill+)>
<!ATTLIST category name CDATA #REQUIRED>
<!ELEMENT skill (#PCDATA)>
<!ELEMENT attributes (attribute+)>
<!ELEMENT attribute (#PCDATA)>
<!ELEMENT interests (interest+)>
<!ELEMENT interest (#PCDATA)>
<!ELEMENT links (link+)>
<!ELEMENT link (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT location (#PCDATA)>
<!ELEMENT availability (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT institution (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT tools (#PCDATA)>
<!ELEMENT duration (#PCDATA)>
<!ELEMENT level (#PCDATA)>

=== AloyseSECK/portfolio_django/portfolio/templates/cv_copy.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="{% static 'portfolio/xslt/cv_style_copy.xslt' %}"?>
<!DOCTYPE resume SYSTEM "structure_cv.dtd">
<resume>
    <personalInfo>
        <name>{% trans "SECK Aloyse Maliam" %}</name>
        <title>{% trans "INGENIEUR INFORMATIQUE EN ALTERNANCE" %}</title>
        <contact>
            <phone>06 01 41 07 98</phone>
            <email>aloysemaliamseck@gmail.com</email>
            <location>{% trans "95330 DOMONT" %}</location>
        </contact>
        <availability>{% trans "Disponibilit√© : D√®s septembre 2023" %}</availability>
        <age>{% trans "22 ans" %}</age>
    </personalInfo>
    <objective>
        {% trans "A la recherche d'un contrat d'apprentissage de 24 mois" %}
        <duration>{% trans "Rythme : Un mois sur deux en entreprise" %}</duration>
    </objective>
    <projects>
        <project>
            <title>{% trans "D√âVELOPPEMENT WEB - SITE E-COMMERCE" %}</title>
            <institution>{% trans "Ecole d'Ing√©nieur Sup Galil√©e" %}</institution>
            <description>{% trans "R√©alis√© en √©quipe de 5 √©tudiants au niveau acad√©mique - D√©velopp√© en PHP - Java Script - Html et CSS" %}</description>
            <tools>{% trans "Wamp/PHPmyadmin - SQL" %}</tools>
        </project>
        <project>
            <title>{% trans "TRANSPORT MONITORING - GPS" %}</title>
            <institution>{% trans "Classes pr√©paratoires Maristes-S√©n√©gal" %}</institution>
            <date>{% trans "Janvier 2021 / Juin 2021" %}</date>
            <description>{% trans "R√©alisation d'un syst√®me de suivi des bus de l'universit√© via GPS - D√©velopp√© en python" %}</description>
            <tools>{% trans "Python3 - SQL alchemy - Flask - Requests - Raspberry Pi" %}</tools>
        </project>
        <project>
            <title>{% trans "LEARNING MACHINE MENACE" %}</title>
            <institution>{% trans "Ecole d'Ing√©nieur Sup Galil√©e" %}</institution>
            <date>{% trans "D√©cembre 2021 / Janvier 2022" %}</date>
            <description>{% trans "IA qui apprend √† jouer au morpion - R√©alis√© en √©quipe de 3 √©tudiants au niveau acad√©mique - D√©velopp√© en C" %}</description>
            <tools>{% trans "Langage C" %}</tools>
        </project>
        <project>
            <title>{% trans "DSP CALCULATOR" %}</title>
            <institution>{% trans "Ecole d'Ing√©nieur Sup Galil√©e" %}</institution>
            <date>{% trans "Mars 2022" %}</date>
            <description>{% trans "Mod√©lisation d'un syst√®me de type factory builder - D√©velopp√© en Java" %}</description>
            <tools>{% trans "Java" %}</tools>
        </project>
    </projects>
    <education>
        <degree>
            <title>{% trans "DIPLOME D'INGENIEUR INFORMATIQUE" %}</title>
            <institution>{% trans "Universit√© Sorbonne Paris Nord, Villetaneuse - France" %}</institution>
            <date>{% trans "2021 / 2025" %}</date>
        </degree>
        <degree>
            <title>{% trans "CLASSE PR√âPARATOIRE" %}</title>
            <institution>{% trans "Institut Mariste Post-BAC, Dakar - S√©n√©gal" %}</institution>
            <date>{% trans "Septembre 2019 / Juin 2021" %}</date>
        </degree>
        <degree>
            <title>{% trans "BACCALAUR√âAT SCIENTIFIQUE" %}</title>
            <institution>{% trans "Ecole Priv√©e Chez Etienne et Monique, S√©n√©gal" %}</institution>
            <date>{% trans "Juillet 2019" %}</date>
        </degree>
    </education>
    <languages>
        <language>
            <name>{% trans "ANGLAIS" %}</name>
            <level>{% trans "Niveau avanc√©" %}</level>
        </language>
        <language>
            <name>{% trans "WOLOF" %}</name>
            <level>{% trans "Langue maternelle" %}</level>
        </language>
    </languages>
    <skills>
        <category name='{% trans "LANGAGES DE PROGRAMMATION" %}'>
            <skill>{% trans "Python" %}</skill>
            <skill>{% trans "Java" %}</skill>
            <skill>{% trans "C" %}</skill>
            <skill>{% trans "Matlab" %}</skill>
        </category>
        <category name='{% trans "TECHNOLOGIES WEB" %}'>
            <skill>{% trans "JavaScript" %}</skill>
            <skill>{% trans "PHP" %}</skill>
            <skill>{% trans "HTML/CSS" %}</skill>
            <skill>{% trans "Django" %}</skill>
            <skill>{% trans "Springboot" %}</skill>
        </category>
        <category name='{% trans "BASE DE DONN√âES" %}'>
            <skill>{% trans "SQL" %}</skill>
            <skill>{% trans "MySQL" %}</skill>
            <skill>{% trans "SQLite" %}</skill>
        </category>
        <category name='{% trans "AUTRES" %}'>
            <skill>{% trans "Json" %}</skill>
            <skill>{% trans "UML" %}</skill>
            <skill>{% trans "XML" %}</skill>
        </category>
        <category name='{% trans "OUTILS &amp; LOGICIELS" %}'>
            <skill>{% trans "Anaconda" %}</skill>
            <skill>{% trans "PyCharm" %}</skill>
            <skill>{% trans "Visual Studio Code" %}</skill>
            <skill>{% trans "Git" %}</skill>
            <skill>{% trans "Github" %}</skill>
            <skill>{% trans "Eclipse" %}</skill>
            <skill>{% trans "WampServer" %}</skill>
            <skill>{% trans "Oracle" %}</skill>
            <skill>{% trans "Pack Office" %}</skill>
        </category>
    </skills>
    <attributes>
        <attribute>{% trans "Autonomie" %}</attribute>
        <attribute>{% trans "Capacit√© d'√©coute et de compr√©hension" %}</attribute>
        <attribute>{% trans "Travail d'√©quipe" %}</attribute>
    </attributes>
    <interests>
        <interest>{% trans "Basketball üèÄ" %}</interest>
        <interest>{% trans "Programmation üíª" %}</interest>
        <interest>{% trans "Musique üéµ" %}</interest>
    </interests>
    <links>
        <link>https://github.com/AloyseSECK</link>
        <link>https://www.linkedin.com/in/aloyse-maliam-seck/</link>
    </links>
</resume>
